spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-bot
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/chat-bot
    user: user
    password: password
    table: flyway_history
  application:
    name: rag
  docker:
    compose:
      lifecycle-management: start_only
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            platform: postgresql
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash-lite
      api-key: ${GEMINI_API_KEY}
      embedding:
        base-url: https://generativelanguage.googleapis.com
        embeddings-path: /v1beta/openai/embeddings
        options:
          model: gemini-embedding-001
          dimensions: 768
    vectorstore:
      pgvector:
        initialize-schema: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true


logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG